[package]
name = "relay"
version = "0.1.0"
edition.workspace = true

[dependencies]
moqt = { path = "../moqt" }
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
quinn.workspace = true
rustls.workspace = true
rustls-pki-types.workspace = true
rcgen.workspace = true
rustls-pemfile = "2"
tokio.workspace = true
url.workspace = true
web-transport-quinn.workspace = true

[dev-dependencies]
cli-lib = { path = "../apps-cli/lib" }
